list = [
    'Pop Rock',
    'House',
    'Experimental',
    'Vocal',
    'Punk',
    'Synth-pop',
    'Alternative Rock',
    'Techno',
    'Disco',
    'Soul',
    'Indie Rock',
    'Hardcore',
    'Ambient',
    'Electro',
    'Hard Rock',
    'Folk',
    'Ballad',
    'Country',
    'Rock & Roll',
    'Trance',
    'Heavy Metal',
    'Chanson',
    'Psychedelic Rock',
    'Classic Rock',
    'Downtempo',
    'Folk Rock',
    'Prog Rock',
    'Noise',
    'Funk',
    'Schlager',
    'Tech House',
    'Easy Listening',
    'New Wave',
    'Blues Rock',
    'Deep House',
    'Euro House',
    'Industrial',
    'Black Metal',
    'Rhythm & Blues',
    'Drum n Bass',
    'Progressive House',
    'Death Metal',
    'Abstract',
    'Soft Rock',
    'Minimal',
    'Garage Rock',
    'Europop',
    'Thrash',
    'Acoustic',
    'RnB/Swing',
    'Dub',
    'Breakbeat',
    'Big Band',
    'Swing',
    'Gospel',
    'Country Rock',
    'Progressive Trance',
    'Contemporary Jazz',
    'Dancehall',
    'Drone',
    'Breaks',
    'IDM',
    'Reggae',
    'Hard Trance',
    'Art Rock',
    'Fusion',
    'Avantgarde',
    'Indie Pop',
    'Doom Metal',
    'Roots Reggae',
    'Gangsta',
    'Pop Rap',
    'African',
    'Jazz-Funk',
    'Rockabilly',
    'Dark Ambient',
    'Beat',
    'Acid',
    'Leftfield',
    'Electro House',
    'Hip Hop',
    'Grindcore',
    'Lo-Fi',
    'Ska',
    'Post-Punk',
    'Dubstep',
    'Hard House',
    'Soul-Jazz',
    'Glam',
    'Goth Rock',
    'Post Rock',
    'Instrumental',
    'Modern Classical',
    'Psy-Trance',
    'Power Pop',
    'Bop',
    'Jazz-Rock',
    'Trip Hop',
    'Italo-Disco',
    'Conscious',
    'Free Improvisation',
    'Dance-pop',
    'New Age',
    'Latin Jazz',
    'Garage House',
    'Hard Bop',
    'Free Jazz',
    'Stoner Rock',
    'Emo',
    'EBM',
    'Happy Hardcore',
    'Symphonic Rock',
    'Surf',
    'Jungle',
    'Oi',
    'Cool Jazz',
    'UK Garage',
    'Shoegaze',
    'Hardstyle',
    'Doo Wop',
    'Post Bop',
    'Tribal',
    'Smooth Jazz',
    'Italodance',
    'J-pop',
    'Bluegrass',
    'Future Jazz',
    'Grunge',
    'Novelty',
    'Celtic',
    'Arena Rock',
    'Latin',
    'Eurodance',
    'Laïkó',
    'Pop Punk',
    'Southern Rock',
    'Darkwave',
    'Dixieland',
    'Gabber',
    'Glitch',
    'Parody',
    'Nu Metal',
    'Volksmusik',
    'Polka',
    'Hi NRG',
    'Hardcore Hip-Hop',
    'Krautrock',
    'Speed Metal',
    'Space Rock',
    'Acid House',
    'Metalcore',
    'Thug Rap',
    'Contemporary R&B',
    'Dub Techno',
    'Brit Pop',
    'Bossa Nova',
    'Synthwave',
    'Reggae-Pop',
    'Hindustani',
    'Power Electronics',
    'Acid Jazz',
    'Musique Concrète',
    'AOR',
    'Big Beat',
    'Breakcore',
    'Freestyle',
    'Progressive Metal',
    'Power Metal',
    'Vaporwave',
    'Electric Blues',
    'Tribal House',
    'Mod',
    'Bollywood',
    'Flamenco',
    'Country Blues',
    'Broken Beat',
    'Trap',
    'Bass Music',
    'Avant-garde Jazz',
    'Chiptune',
    'Jazzy Hip-Hop',
    'Modal',
    'Rocksteady',
    'Harsh Noise Wall',
    'Math Rock',
    'Chicago Blues',
    'Neofolk',
    'Marches',
    'Calypso',
    'Ethereal',
    'Afrobeat',
    'Boom Bap',
    'Grime',
    'Sludge Metal',
    'Goa Trance',
    'Boogie',
    'Lounge',
    'Psychedelic',
    'Hip-House',
    'Lovers Rock',
    'Neo Soul',
    'Minimal Techno',
    'Post-Hardcore',
    'Rhythmic Noise',
    'Ragtime',
    'Cut-up/DJ',
    'Psychobilly',
    'Crust',
    'Indian Classical',
    'Ragga',
    'Éntekhno',
    'Ragga HipHop',
    'Nu-Disco',
    'Pacific',
    'Speedcore',
    'G-Funk',
    'Gothic Metal',
    'Euro-Disco',
    'Space-Age',
    'Light Music',
    'Brass Band',
    'Berlin-School',
    'Funk Metal',
    'Tech Trance',
    'Kayōkyoku',
    'Makina',
    'Jazzdance',
    'Fado',
    'Highlife',
    'Twist',
    'Honky Tonk',
    'Music Hall',
    'Afro-Cuban Jazz',
    'Acid Rock',
    'Canzone Napoletana',
    'Nordic',
    'Melodic Death Metal',
    'Dungeon Synth',
    'Military',
    'Soca',
    'New Jack Swing',
    'Deep Techno',
    'Eurobeat',
    'New Beat',
    'Delta Blues',
    'Melodic Hardcore',
    'Zouk',
    'Chillwave',
    'Piano Blues',
    'Goregrind',
    'Soukous',
    'Modern Electric Blues',
    'Folk Metal',
    'Hard Techno',
    'Horrorcore',
    'Viking Metal',
    'Jumpstyle',
    'Romani',
    'Speed Garage',
    'Sound Collage',
    'Gypsy Jazz',
    'Hawaiian',
    'Deathcore',
    'P.Funk',
    'Harmonica Blues',
    'Texas Blues'
]